baseurl      = "yujia21.github.io"
title        = "Yu Jia's Website"
languageCode = "en-us"
theme        = "hello-friend-ng"
pagination.pagerSize     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Hello! Welcome to my site. Here, you can find my technical portfolio and some of my writing (we contain multitudes)."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "Yu Jia's Website"
  keywords = "homepage, blog, data science, software engineering, python, portfolio"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "yujia21"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.en.params]
    subtitle  = ""

    [languages.en.params.logo]
      logoText = "home"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"

  [[menu.main]]
    identifier = "portfolio"
    name       = "Tech Portfolio"
    url        = "/portfolio"

  [[menu.main]]
    identifier = "writing"
    name       = "Writing"
    url        = "/writing"

  [[params.social]]
    name = "email"
    url = "mailto:yujia21.writes@gmail.com"
  [[params.social]]
    name = "github"
    url = "https://github.com/yujia21/"
  [[params.social]]
    name = "gitlab"
    url = "https://gitlab.com/yujia21/"
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/yujia21/"
